# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gW3Q36y57geMcGdQB8J4zrkYRwQbUBfa
"""

from setuptools import setup, find_packages

setup(
    name='py4stats',  # パッケージ名（pip listで表示される）
    version="0.0.1",  # バージョン
    description="sample tools for regression analisys",  # 説明
    author='Hiroto Tensho',  # 作者名
    packages = find_packages(),  # 使うモジュール一覧を指定する
    license='MIT',  # ライセンス
)