# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Urm8aX1VIPFmIrKlp5f34yEJmIaG3I-
"""

from py4stats import *
# from regression_tools import *
# from eda_tools import *

__all__ = ['load']

__author__ = 'Hiroto Tensho'
__version__ = '0.0.1'
__copyright__ = 'Copyright (c) 2024 Hiroto Tensho'
