# -*- coding: utf-8 -*-

# eda_tools --------------------------------------------

from .eda_tools.operation import (
    bind_rows,
    compare_df_cols,
    compare_df_record,
    compare_df_stats,
    compare_group_means,
    compare_group_median,
    complete,
    crosstab,
    diagnose,
    diagnose_category,
    expand,
    filtering_out,
    freq_table,
    group_split, 
    group_map, 
    group_modify,
    info_gain,
    is_dummy,
    is_number,
    is_ymd_like,
    is_ymd,
    mean_ci,
    mean_qi,
    median_qi,
    min_max,
    scale,
    set_miss,
    relocate,
    remove_constant,
    remove_empty,
    tabyl,
    weighted_mean
)

from .eda_tools.reviewing import (
    Max,
    Mean,
    Median,
    Min,
    Sum,
    implies_exper,
    review_wrangling,
    review_shape,
    review_col_addition,
    review_casting,
    review_missing,
    review_category,
    review_numeric,
    check_that,
    check_viorate,
)

from .eda_tools.visualize import (
    Pareto_plot,
    plot_category,
    plot_count_h,
    plot_mean_diff,
    plot_median_diff,
    plot_miss_var,
)

## regression_tools --------------------------------------------
from .regression_tools import (
    Blinder_Oaxaca, 
    add_one_sided_p_value, 
    coefplot, 
    compare_mfx, 
    compare_ols, 
    glance, 
    glance_glm, 
    glance_ols, 
    log_to_pct, 
    mfxplot, 
    overload, 
    plot_Blinder_Oaxaca, 
    tidy, 
    tidy_mfx, 
    tidy_to_jp
    )


__all__ = [
    # 'load',
    # eda_tools --------------------------------------------
    'Max',
    'Mean',
    'Median',
    'Min',
    'Pareto_plot',
    'Sum',
    'bind_rows',
    'check_that',
    'check_viorate',
    'compare_df_cols',
    'compare_df_record',
    'compare_df_stats',
    'compare_group_means',
    'compare_group_median',
    'complete',
    'crosstab',
    'diagnose',
    'diagnose_category',
    'expand',
    'filtering_out',
    'freq_table',
    'group_map',
    'group_modify',
    'group_split',
    'implies_exper',
    'info_gain',
    'is_dummy',
    'is_number',
    'is_ymd',
    'is_ymd_like',
    'mean_ci',
    'mean_qi',
    'median_qi',
    'min_max',
    'plot_category',
    'plot_mean_diff',
    'plot_median_diff',
    'plot_miss_var',
    'relocate',
    'remove_constant',
    'remove_empty',
    'review_casting',
    'review_category',
    'review_col_addition',
    'review_missing',
    'review_numeric',
    'review_shape',
    'review_wrangling',
    'scale',
    'set_miss',
    'tabyl',
    'weighted_mean',

    ## regression_tools --------------------------------------------
    'Blinder_Oaxaca',
    'add_one_sided_p_value',
    'coefplot',
    'compare_mfx',
    'compare_ols',
    'glance',
    'glance_glm',
    'glance_ols',
    'log_to_pct',
    'mfxplot',
    'overload',
    'plot_Blinder_Oaxaca',
    'tidy',
    'tidy_mfx',
    'tidy_to_jp'
    ]

__author__ = 'Hiroto Tensho'
__version__ = '0.5.1'
__copyright__ = 'Copyright (c) 2024-2026 Hiroto Tensho'