# データ型による引数のアサーション

## 概要

　R言語の [`checkmate`](https://mllg.github.io/checkmate/index.html) パッケージの関数群をオマージュした、引数に代入された値が想定されたデータ型ではないときにエラーを出力する関数です。

``` python
assert_character(
    arg: Any, 
    arg_name: Optional[str] = None,
    len_arg: Optional[int] = None,
    len_min: int = 1,
    len_max: Optional[int] = None,
    any_missing: bool = False,
    all_missing: bool = False,
    nullable: bool = False,
    scalar_only: bool = False
    )

assert_logical(
    arg: Any, 
    arg_name: Optional[str] = None,
    len_arg: Optional[int] = None,
    len_min: int = 1,
    len_max: Optional[int] = None,
    any_missing: bool = False,
    all_missing: bool = False,
    nullable: bool = False,
    scalar_only: bool = False
    )

assert_numeric(
    arg: Any,
    arg_name: Optional[str] = None,
    lower = -float('inf'), 
    upper = float('inf'), 
    inclusive: Literal["both", "neither", "left", "right"] = "both",
    len_arg: Optional[int] = None,
    len_min: int = 1,
    len_max: Optional[int] = None,
    any_missing: bool = False,
    all_missing: bool = False,
    nullable: bool = False,
    scalar_only: bool = False
    )

assert_integer(
    arg: Any,
    arg_name: Optional[str] = None,
    lower = -float('inf'), 
    upper = float('inf'), 
    inclusive: Literal["both", "neither", "left", "right"] = "both",
    len_arg: Optional[int] = None,
    len_min: int = 1,
    len_max: Optional[int] = None,
    any_missing: bool = False,
    all_missing: bool = False,
    nullable: bool = False,
    scalar_only: bool = False
    )

assert_count(
    arg: Any,
    arg_name: Optional[str] = None,
    lower = 0, 
    upper = float('inf'), 
    inclusive: Literal["both", "neither", "left", "right"] = "both",
    len_arg: Optional[int] = None,
    len_min: int = 1,
    len_max: Optional[int] = None,
    any_missing: bool = False,
    all_missing: bool = False,
    nullable: bool = False,
    scalar_only: bool = False
    )

assert_float(
    arg: Any,
    arg_name: Optional[str] = None,
    lower = -float('inf'), 
    upper = float('inf'), 
    inclusive: Literal["both", "neither", "left", "right"] = "both",
    len_arg: Optional[int] = None,
    len_min: int = 1,
    len_max: Optional[int] = None,
    any_missing: bool = False,
    all_missing: bool = False,
    nullable: bool = False,
    scalar_only: bool = False
    )
```

　それぞれの関数は第一引数 `arg` に代入された array-like オブジェクトの要素が、次の型ではない場合にエラーを出力します。

- `assert_character()`：**str**
- `assert_numeric()`：**int or float**
- `assert_integer()`：**int**
- `assert_count()`：**int**
- `assert_float()`：**float**

## 引数 Argument

- `arg`（必須）**array-like**</br>
　適正かどうかを判断したい引数。検証対象となる引数。スカラー値、または array-like オブジェクト（例：list、NumPy 配列、pandas Series）を指定できます。
- `arg_name`：**str**</br>
　エラーメッセージに表示する引数の名前。`None` の場合、可能であれば `arg` に渡された変数名が自動的に推定されます。なお、この機能は [`varname.argname()`](https://github.com/pwwang/python-varname?tab=readme-ov-file)関数を使って実装されています。
- `lower`, `upper`：**int or float**</br>
　`arg` に代入されたオブジェクトの要素が取るべき値の最大値と最小値。
- inclusive：**str**</br>
　値の範囲チェックにおいて、境界値を含めるかどうかを表す文字列。</br>
`'both', 'neither', 'left', 'right'` から選択できます。</br>
    - `'both'`：`lower <= x <= upper`
    - `'neither'`：`lower < x < upper`
    - `'left'`：`lower <= x < upper`
    - `'right'`：`lower < x <= upper`
- `len_arg`: **int**
引数の要素数を表す自然数：要素数をこの値と**正確に一致させたい場合**に指定します。`len_arg` を指定した場合、引数はちょうどこの個数の要素をもつ必要があります。</br>
　引数の長さは、`None` や `np.nan` などの欠測値を**含む要素数**をもとに判定されます。例えば引数の要素が `arg = [1, None, 3]` のとき、`len_arg = 3`なら正常として判定され、`len_arg = 2` ならエラーが出されます。
* `len_min`, `len_max`:: **int**</br>
  許容される最小の要素数と最大の要素数。`len_max = None` の場合、上限は設けられません。
* `any_missing`:**bool**</br>
  `True` の場合、欠測値（例：`None`、`NaN`、`pd.NA` など）が引数 `arg` の**一部に含まれていても許容**されます。
* `all_missing`: **bool**</br>
  `True` の場合、すべての要素が欠測値であることを許容します。
* `nullable`: **bool**</br>
  `True` の場合、引数そのものが `None` であることを許容します。
* `scalar_only`: **bool**</br>
  `True` の場合、スカラー値のみを許容します。この場合、1要素であっても、list や配列などの array-like オブジェクトは受け付けません。


## 返り値 Value

引数 `arg` に代入されたオブジェクトの全ての要素が、アサーションの条件を満たしていれば何も返さず、そうでなければエラーメッセージを出力します。

## 使用例 Examples

```python
from py4stats import building_block as build
x = [1, 2, 3]
y = ['A', 'B', 'C']

build.assert_character(x, arg_name = 'x')
#> TypeError: Argument `x` must be of type 'str'.

build.assert_character(y, arg_name = 'y')
```

```python
build.assert_numeric(x, arg_name = 'x')

build.assert_numeric(y, arg_name = 'y')
#> TypeError: Argument `y` must be of type 'int' or 'float' with value(s) -inf <= x <= inf.

z = [0.1, 0.3, 0.6]
build.assert_numeric(z, arg_name = 'z', lower = 0, upper = 1)

z.extend([2, 3])
build.assert_numeric(z, arg_name = 'z', lower = 0, upper = 1)
#> ValueError: Argument `z` must have value 0 <= x <= 1
#> element '3' and '4' of 'z' not sutisfy the condtion.

z = 1
build.assert_numeric(
    z, arg_name = 'z', 
    lower = 0, upper = 1, 
    inclusive = 'left'
    )
#> ValueError: Argument `z` must have value 0 <= x < 1.
```

## 参照

　データ型の判定には[こちらの関数](./is_dtype.qmd)を使用しています。

***
[Return to **Function reference**.](../reference.qmd)
