# -*- coding: utf-8 -*-
from ._nw import (
    Max,
    Mean,
    Median,
    Min,
    Pareto_plot,
    Sum,
    check_that,
    check_viorate,
    compare_df_cols,
    compare_df_record,
    compare_df_stats,
    compare_group_means,
    compare_group_median,
    crosstab,
    diagnose,
    diagnose_category,
    filtering_out,
    freq_table,
    group_split, 
    group_map, 
    group_modify,
    implies_exper,
    is_dummy,
    is_number,
    is_ymd_like,
    is_ymd,
    mean_ci,
    mean_qi,
    median_qi,
    min_max,
    plot_category,
    plot_mean_diff,
    plot_median_diff,
    plot_miss_var,
    scale,
    set_miss,
    relocate,
    remove_constant,
    remove_empty,
    review_wrangling,
    review_shape,
    review_col_addition,
    review_casting,
    review_missing,
    review_category,
    review_numeric,
    tabyl,
    weighted_mean
)

from ._pandas import (
    Max, 
    Mean, 
    Median, 
    Min, 
    Pareto_plot, 
    Sum, 
    check_that, 
    check_viorate, 
    compare_df_cols, 
    compare_df_record, 
    compare_df_stats, 
    compare_group_means, 
    compare_group_median, 
    crosstab2, 
    detect_Kanzi, 
    diagnose, 
    diagnose_category, 
    entropy, 
    filtering_out, 
    freq_mode, 
    freq_table, 
    implies_exper, 
    is_complet, 
    is_dummy, 
    is_number, 
    is_ymd, 
    is_ymd_like, 
    itertools, 
    mean_ci, 
    mean_qi, 
    median_qi, 
    min_max, 
    missing_percent, 
    plot_mean_diff, 
    plot_median_diff, 
    remove_constant, 
    remove_empty, 
    set_n_miss, 
    set_prop_miss, 
    singledispatch, 
    std_entropy, 
    tabyl , 
    weighted_mean
    )


__all__ = [
    # 'load',
    # eda_tools --------------------------------------------
    'Max',
    'Mean',
    'Median',
    'Min',
    'Pareto_plot',
    'Sum',
    'check_that',
    'check_viorate',
    'compare_df_cols',
    'compare_df_record',
    'compare_df_stats',
    'compare_group_means',
    'compare_group_median',
    'crosstab',
    # 'is_kanzi',
    'diagnose',
    'diagnose_category',
    'entropy',
    'filtering_out',
    'freq_mode',
    'freq_table',
    'implies_exper',
    'is_complet',
    'is_dummy',
    'is_number',
    'is_ymd',
    'is_ymd_like',
    'itertools',
    'mean_ci',
    'mean_qi',
    'median_qi',
    'min_max',
    'missing_percent',
    'plot_mean_diff',
    'plot_median_diff',
    'remove_constant',
    'remove_empty',
    # 'set_miss',
    # 'set_prop_miss',
    'review_wrangling'
    'singledispatch',
    'normalized_entropy',
    'tabyl',
    'weighted_mean'
    ]

