# -*- coding: utf-8 -*-

# from ._nw import (
#     Max,
#     Mean,
#     Median,
#     Min,
#     Pareto_plot,
#     Sum,
#     bind_rows,
#     check_that,
#     check_viorate,
#     compare_df_cols,
#     compare_df_record,
#     compare_df_stats,
#     compare_group_means,
#     compare_group_median,
#     crosstab,
#     diagnose,
#     diagnose_category,
#     filtering_out,
#     freq_table,
#     group_split, 
#     group_map, 
#     group_modify,
#     info_gain,
#     implies_exper,
#     is_dummy,
#     is_number,
#     is_ymd_like,
#     is_ymd,
#     mean_ci,
#     mean_qi,
#     median_qi,
#     min_max,
#     plot_category,
#     plot_mean_diff,
#     plot_median_diff,
#     plot_miss_var,
#     scale,
#     set_miss,
#     relocate,
#     remove_constant,
#     remove_empty,
#     review_wrangling,
#     review_shape,
#     review_col_addition,
#     review_casting,
#     review_missing,
#     review_category,
#     review_numeric,
#     tabyl,
#     weighted_mean
# )

from .opration import (
    Pareto_plot,
    bind_rows,
    compare_df_cols,
    compare_df_record,
    compare_df_stats,
    compare_group_means,
    compare_group_median,
    crosstab,
    diagnose,
    diagnose_category,
    filtering_out,
    freq_table,
    group_split, 
    group_map, 
    group_modify,
    info_gain,
    is_dummy,
    is_number,
    is_ymd_like,
    is_ymd,
    mean_ci,
    mean_qi,
    median_qi,
    min_max,
    plot_category,
    plot_mean_diff,
    plot_median_diff,
    plot_miss_var,
    scale,
    set_miss,
    relocate,
    remove_constant,
    remove_empty,
    tabyl,
    weighted_mean
    # Max,
    # Mean,
    # Median,
    # Min,
    # Sum,
    # implies_exper,
    # check_that,
    # check_viorate,
    # review_wrangling,
    # review_shape,
    # review_col_addition,
    # review_casting,
    # review_missing,
    # review_category,
    # review_numeric,
)
from .reviewing import (
    Max,
    Mean,
    Median,
    Min,
    Sum,
    implies_exper,
    review_wrangling,
    review_shape,
    review_col_addition,
    review_casting,
    review_missing,
    review_category,
    review_numeric,
    check_that,
    check_viorate,
)

__all__ = [
    # eda_tools --------------------------------------------
    'Max',
    'Mean',
    'Median',
    'Min',
    'Pareto_plot',
    'Sum',
    'bind_rows',
    'check_that',
    'check_viorate',
    'compare_df_cols',
    'compare_df_record',
    'compare_df_stats',
    'compare_group_means',
    'compare_group_median',
    'crosstab',
    'diagnose',
    'diagnose_category',
    'filtering_out',
    'freq_table',
    'group_map',
    'group_modify',
    'group_split',
    'implies_exper',
    'info_gain',
    'is_dummy',
    'is_number',
    'is_ymd',
    'is_ymd_like',
    'mean_ci',
    'mean_qi',
    'median_qi',
    'min_max',
    'plot_category',
    'plot_mean_diff',
    'plot_median_diff',
    'plot_miss_var',
    'relocate',
    'remove_constant',
    'remove_empty',
    'review_casting',
    'review_category',
    'review_col_addition',
    'review_missing',
    'review_numeric',
    'review_shape',
    'review_wrangling',
    'scale',
    'set_miss',
    'tabyl',
    'weighted_mean'
    ]

