# -*- coding: utf-8 -*-
from ._nw import (
    Max,
    Mean,
    Median,
    Min,
    Pareto_plot,
    Sum,
    check_that,
    check_viorate,
    compare_df_cols,
    compare_df_record,
    compare_df_stats,
    compare_group_means,
    compare_group_median,
    crosstab,
    diagnose,
    filtering_out,
    freq_table,
    implies_exper,
    is_dummy,
    is_number,
    is_ymd_like,
    is_ymd,
    mean_ci,
    mean_qi,
    median_qi,
    min_max,
    missing_percent,
    plot_mean_diff,
    plot_median_diff,
    plot_miss_var,
    remove_constant,
    tabyl,
    weighted_mean
)

from ._pandas import (
    Max, 
    Mean, 
    Median, 
    Min, 
    Pareto_plot, 
    Sum, 
    check_that, 
    check_viorate, 
    compare_df_cols, 
    compare_df_record, 
    compare_df_stats, 
    compare_group_means, 
    compare_group_median, 
    crosstab2, 
    detect_Kanzi, 
    diagnose, 
    diagnose_category, 
    entropy, 
    filtering_out, 
    freq_mode, 
    freq_table, 
    implies_exper, 
    is_complet, 
    is_dummy, 
    is_number, 
    is_ymd, 
    is_ymd_like, 
    itertools, 
    mean_ci, 
    mean_qi, 
    median_qi, 
    min_max, 
    missing_percent, 
    plot_mean_diff, 
    plot_median_diff, 
    remove_constant, 
    remove_empty, 
    # set_n_miss, 
    # set_prop_miss, 
    singledispatch, 
    std_entropy, 
    tabyl , 
    weighted_mean
    )


# from ._nw import (
#     diagnose_nw,
#     plot_missing,
#     compare_df,
# )

# __all__ = [
#     "diagnose_nw",
#     "plot_missing",
#     "compare_df",
# ]

# __all__ = [
#     # 'load',
#     ## eda_tools --------------------------------------------
#     # 'Max',
#     # 'Mean',
#     # 'Median',
#     # 'Min',
#     # 'Pareto_plot',
#     # 'Sum',
#     # 'check_that',
#     # 'check_viorate',
#     # 'compare_df_cols',
#     # 'compare_df_record',
#     # 'compare_df_stats',
#     # 'compare_group_means',
#     # 'compare_group_median',
#     # 'crosstab2',
#     # 'detect_Kanzi',
#     # 'diagnose',
#     # 'diagnose_category',
#     # 'entropy',
#     # 'filtering_out',
#     # 'freq_mode',
#     # 'freq_table',
#     # 'implies_exper',
#     # 'is_complet',
#     # 'is_dummy',
#     # 'is_number',
#     # 'is_ymd',
#     # 'is_ymd_like',
#     # 'itertools',
#     # 'mean_ci',
#     # 'mean_qi',
#     # 'median_qi',
#     # 'min_max',
#     # 'missing_percent',
#     # 'plot_mean_diff',
#     # 'plot_median_diff',
#     # 'remove_constant',
#     # 'remove_empty',
#     # 'set_n_miss',
#     # 'set_prop_miss',
#     # 'singledispatch',
#     # 'std_entropy',
#     # 'tabyl',
#     # 'weighted_mean',

#     ## regression_tools --------------------------------------------
#     'Blinder_Oaxaca',
#     'add_one_sided_p_value',
#     'coefplot',
#     'compare_mfx',
#     'compare_ols',
#     'glance',
#     'glance_glm',
#     'glance_ols',
#     'log_to_pct',
#     'mfxplot',
#     'overload',
#     'plot_Blinder_Oaxaca',
#     'tidy',
#     'tidy_mfx',
#     'tidy_to_jp'
#     ]

